package com.penguenlabs.pushnote.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF5E4CBE)
val md_theme_light_primaryContainer = Color(0xFFE5DEFF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF1A0063)
val md_theme_light_secondary = Color(0xFF605C71)
val md_theme_light_secondaryContainer = Color(0xFFE5DFF9)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_onSecondaryContainer = Color(0xFF1C192B)
val md_theme_light_tertiary = Color(0xFF7C5264)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8E6)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_onTertiaryContainer = Color(0xFF301120)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF79757F)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE5E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF48454E)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inversePrimary = Color(0xFFC9BFFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF5E4CBE)
val md_theme_light_outlineVariant = Color(0xFFC9C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFC9BFFF)
val md_theme_dark_primaryContainer = Color(0xFF4631A5)
val md_theme_dark_onPrimary = Color(0xFF2F118F)
val md_theme_dark_onPrimaryContainer = Color(0xFFE5DEFF)
val md_theme_dark_secondary = Color(0xFFC9C3DC)
val md_theme_dark_secondaryContainer = Color(0xFF484459)
val md_theme_dark_onSecondary = Color(0xFF312E41)
val md_theme_dark_onSecondaryContainer = Color(0xFFE5DFF9)
val md_theme_dark_tertiary = Color(0xFFEDB8CD)
val md_theme_dark_tertiaryContainer = Color(0xFF623B4C)
val md_theme_dark_onTertiary = Color(0xFF482536)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE5E1E6)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE5E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF48454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9C5D0)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E6)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inversePrimary = Color(0xFF5E4CBE)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFC9BFFF)
val md_theme_dark_outlineVariant = Color(0xFF48454E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF6E5CCF)
